insert into Role (id, name) values (1, 'ADMIN');
insert into Role (id, name) values (2, 'REFEREE');
insert into License (id, type) values (1, 'CANDIDATE');
insert into License (id, type) values (2, 'THIRD_CLASS');
insert into License (id, type) values (3, 'SECOND_CLASS');
insert into License (id, type) values (4, 'FIRST_CLASS');
insert into League (id, name) values (1, 'FIRST');
insert into League (id, name) values (2, 'SECOND');
insert into Account (id, username, email, is_active, version) values (1, 'szymon', 'szymon@edu.p.lodz.pl', true, 0);
insert into Referee (id, name, surname, account_id, role_id, license_id, version) values (1, 'szymon', 'dobrowolski', 1, 1, 1, 0);
